#!/usr/bin/env bash
set -xeuo pipefail
lein jar
# make sure we don't cheat by using src
mkdir -p outside-of-classpath
cd outside-of-classpath
jank --module-path '../target/look-inside-jars-0.1.0-SNAPSHOT.jar' run-main look-inside-jars.core | grep 'LOADED look-inside-jars.core'
