#pragma once

#include <jtl/ptr.hpp>

namespace jank::analyze::cppinterop
{
  using clang_type = jtl::ptr<void>;
  using clang_decl = jtl::ptr<void>;

  //BestOverloadMatch
  //CreateInterpreter
  //DetectResourceDir
  //EnableDebugOutput
  //GetArrayElementType
  //GetArraySize
  //GetArrayType
  //GetBaseClass
  //GetCanonicalType
  //GetCommonType
  //GetDatamembers
  //GetFunctionArgName
  //GetFunctionArgType
  //GetFunctionArgTypeFromType
  //GetFunctionNumArgs
  //GetFunctionNumArgsFromType
  //GetFunctionRequiredArgs
  //GetFunctionReturnType
  //GetFunctionReturnTypeFromType
  //GetFunctionSignature
  //GetFunctionSourceInfo
  //GetFunctionType
  //GetFunctionTypeFromPointerToMember
  //GetFunctionsUsingName
  //GetGlobalScope
  //GetLValueReferenceType
  //GetLongType
  //GetName
  //GetNamed
  //GetNonReferenceType
  //GetNumBases
  //GetOperator
  //GetOverloadCandidateInfo
  //GetParentScope
  //GetParentTypeFromPointerToMember
  //GetPointeeType
  //GetPointerToMemberType
  //GetPointerType
  //GetQualifiedCompleteName
  //GetQualifiedCompleteNameWithTemplateArgs
  //GetQualifiedName
  //GetRValueReferenceType
  //GetScopeFromCompleteName
  //GetScopeFromType
  //GetShortType
  //GetSignedType
  //GetStaticDatamembers
  //GetType
  //GetTypeAsString
  //GetTypeAsTruncatedString
  //GetTypeFromScope
  //GetTypeWithConst
  //GetTypeWithVolatile
  //GetTypeWithoutCv
  //GetUnderlyingScope
  //GetUnderlyingType
  //GetUnsignedType
  //GetVariableOffset
  //GetVoidType
  //HasDeletedMoveConstructor
  //HasUsableCopyConstructor
  //HasUsableMoveConstructor
  //InstantiateTemplate
  //IsArrayType
  //IsBuiltin
  //IsCStyleConvertible
  //IsClassTemplate
  //IsComplete
  //IsConstMethod
  //IsConstType
  //IsConstructible
  //IsDestructor
  //IsEnumConstant
  //IsEnumScope
  //IsEnumType
  //IsFunction
  //IsFunctionDeleted
  //IsFunctionPointerType
  //IsFunctionTypeConst
  //IsFunctionVariadic
  //IsFunctionVariadicTemplate
  //IsImplicitlyConvertible
  //IsInlineFriendFunction
  //IsIntegral
  //IsMethod
  //IsNamespace
  //IsPointerToMemberFunctionType
  //IsPointerToMemberType
  //IsPointerToMemberVariableType
  //IsPointerType
  //IsPrivateMethod
  //IsPrivateVariable
  //IsProtectedMethod
  //IsProtectedVariable
  //IsReferenceType
  //IsRvalueReferenceType
  //IsShortType
  //IsStaticMethod
  //IsStaticVariable
  //IsTemplate
  //IsTemplateSpecialization
  //IsTemplateSpecializationOf
  //IsTemplatedFunction
  //IsTriviallyDestructible
  //IsTypeDerivedFrom
  //IsTypedefed
  //IsVariable
  //IsVoid
  //LookupConstructors
  //LookupDatamember
  //LookupMethods
  //MangleRTTI
  //OverloadCandidateConversion
  //OverloadCandidateInfo
}
