name: Report a bug / crash
description: A bug is when the program is not behaving as you'd expect while a crash is defined as the case where the program exits unexpectedly (Segmentation fault, etc.).
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: jank health check
      description: |
        Output from the `jank check-health` command. Ensure that you wrap the output in three backticks.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description of the issue with reproduction steps
      description: |
        Provide a step-by-step guide on how to reproduce the issue.

        The more context, the better:
        - The exact `jank` command you ran.
        - The code being executed.
        - Any additional setup details (e.g., third-party dependencies) not covered above.

        Be as descriptive as needed. More detail helps us reproduce and fix the issue faster.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Stack trace
      description: |
        If the crash involves a segmentation fault, please include a stack trace.

        The steps differ slightly between `lldb` (commonly used on macOS) and `gdb` (commonly used on Linux).
        - Run the `jank` binary inside the debugger.
        - Run the program by typing `r` in the debugger REPL.
        - Follow your reproduction steps until the program crashes.
        - When it crashes, you will return to the debugger REPL.
        - Type `bt` and paste the output here.
          - Ensure the output is properly formatted, with all stack frames (`frame #<n>`) listed in ascending order.
    validations:
      required: false
