blank_issues_enabled: false
contact_links:
  - name: The official jank Slack
    url: https://clojurians.net/
    about: Join us and ask your questions in Slack!
  - name: The official jank Discord
    url: https://discord.gg/7sSMfKDBU3
    about: Join us and ask your questions in Discord!
