function(jank_message msg)
  message(STATUS "${msg}")
endfunction()

jank_message("┌─ jank options ─────────────────────")
jank_message("│ jank build type     : ${CMAKE_BUILD_TYPE}")
jank_message("│ jank version        : ${jank_version}")
jank_message("│ jank phase 2        : ${jank_enable_phase_2}")
jank_message("│ jank tests          : ${jank_test}")
jank_message("│ jank coverage       : ${jank_coverage}")
jank_message("│ jank analyze        : ${jank_analyze}")
jank_message("│ jank sanitize       : ${jank_sanitize}")
jank_message("│ jank unity build    : ${jank_unity_build}")
jank_message("│ jank resource dir   : ${jank_resource_dir}")
jank_message("│ jank debug gc       : ${jank_debug_gc}")
jank_message("│ jank profile gc     : ${jank_profile_gc}")
jank_message("│ clang version       : ${LLVM_PACKAGE_VERSION}")
jank_message("│ clang prefix        : ${CLANG_INSTALL_PREFIX}")
jank_message("│ clang resource dir  : ${clang_resource_dir}")
jank_message("└─────────────────────────────────────")
