name: Build compiler+runtime (Windows)

on:
  pull_request:
    paths:
      - 'compiler\+runtime/**'
  push:
    branches:
      - main
    paths:
      - 'compiler\+runtime/**'
  workflow_dispatch:

permissions:
  contents: read

# Only allow one build per branch at a time. New builds will cancel existing builds.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Rather than having every job in the matrix try to build its own Clang, we build it once
  # before running the matrix. Then we can just restore it from the cache in each job.
  windows-build-clang:
    name: Windows - build LLVM/Clang
    runs-on: windows-2022
    timeout-minutes: 200
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          environments: default
      - name: Cache Clang/LLVM
        id: clang-cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: |
            ${{ github.workspace }}/compiler+runtime/build/llvm-install
          key: clang-${{ runner.os }}-${{ hashFiles('compiler+runtime/bin/build-clang.nu') }}
      - name: Build Clang/LLVM
        if: steps.clang-cache.outputs.cache-hit != 'true'
        run: pixi run build-clang

  build-jank:
    needs:
      - windows-build-clang
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows - debug, analysis
            os: windows-2022
            build_type: Debug
            sanitize: none
            analyze: on
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    env:
      JANK_MATRIX_ID: ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.sanitize }}
      JANK_BUILD_TYPE: ${{ matrix.build_type }}
      JANK_ANALYZE: ${{ matrix.analyze }}
      JANK_SANITIZE: ${{ matrix.sanitize }}
      ASAN_OPTIONS: detect_leaks=0
      TERM: xterm
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          environments: default
      - name: Prepare Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'
      - name: Cache Clang/LLVM
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: |
            ${{ github.workspace }}/compiler+runtime/build/llvm-install
          key: clang-${{ runner.os }}-${{ hashFiles('compiler+runtime/bin/build-clang.nu') }}
      - name: Cache ccache object files
        if: matrix.analyze == 'off'
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: |
            ${{ github.workspace }}/compiler+runtime/.ccache
          key: ccache-${{ env.JANK_MATRIX_ID }}-${{ github.ref_name }}
      - name: Cache ctcache object files
        if: matrix.analyze == 'on'
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: |
            ${{ github.workspace }}/compiler+runtime/.ctcache
          key: ctcache-${{ env.JANK_MATRIX_ID }}-${{ github.ref_name }}
      - name: Build and test jank
        run: |
          pixi run configure -- -GNinja -Djank_local_clang=on -Djank_test=on -Djank_unity_build=on "-DCMAKE_BUILD_TYPE=${{ matrix.build_type }}" "-Djank_analyze=${{ matrix.analyze }}" "-Djank_sanitize=${{ matrix.sanitize }}" -Djank_force_phase_2=on
          pixi run build
          pixi run test
