name: Daily package check

on:
  schedule:
    # 10:00 AM Pacific Standard Time (doesn't handle DST).
    - cron: "0 18 * * *"
  # Allow manual runs of this workflow.
  workflow_dispatch:

permissions:
  contents: read

# Only allow one build at a time. New builds will cancel existing builds.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  macos-binary-package-test:
    runs-on: macos-26
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install jank
        run: brew install jank-lang/jank/jank clojure/tools/clojure

      - uses: ./.github/actions/e2e-test

  ubuntu-binary-package-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Bootstrap system
        run: |
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
          chmod +x linux-install.sh
          sudo ./linux-install.sh

      - name: Install jank
        run: |
          sudo apt install -y curl gnupg
          curl -s "https://ppa.jank-lang.org/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/jank.gpg >/dev/null
          sudo curl -s -o /etc/apt/sources.list.d/jank.list "https://ppa.jank-lang.org/jank.list"
          sudo apt update
          sudo apt install -y jank

      - uses: ./.github/actions/e2e-test

  arch-binary-package-test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Bootstrap system
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git jre-openjdk-headless
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
          chmod +x linux-install.sh
          sudo ./linux-install.sh

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Create build user for yay
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          su builder -c "git clone https://aur.archlinux.org/yay.git /home/builder/yay"
          su builder -c "cd /home/builder/yay && makepkg -si --noconfirm"

      - name: Install jank
        run: su builder -c "yay -S --noconfirm jank-bin"

      - uses: ./.github/actions/e2e-test
