name: Weekly package check

# TODO: Run the e2e test suite after health check.

on:
  schedule:
    # 10:00 AM Pacific Standard Time (doesn't handle DST).
    - cron: "0 18 * * 1"
  # Allow manual runs of this workflow.
  workflow_dispatch:

# Only allow one build at a time. New builds will cancel existing builds.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  macos-binary-package-test:
    runs-on: macos-26
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Install jank
        run: brew install jank-lang/jank/jank

      - name: Check health
        run: jank check-health || exit 1

  ubuntu-binary-package-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Install jank
        run: |
          sudo apt install -y curl gnupg
          curl -s "https://ppa.jank-lang.org/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/jank.gpg >/dev/null
          sudo curl -s -o /etc/apt/sources.list.d/jank.list "https://ppa.jank-lang.org/jank.list"
          sudo apt update
          sudo apt install -y jank

      - name: Check health
        run: jank check-health || exit 1

  arch-binary-package-test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Bootstrap system
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git

      - name: Create build user for yay
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          su builder -c "git clone https://aur.archlinux.org/yay.git /home/builder/yay"
          su builder -c "cd /home/builder/yay && makepkg -si --noconfirm"

      - name: Install jank
        run: su builder -c "yay -S --noconfirm jank-bin"

      - name: Check health
        run: jank check-health || exit 1
